### ISSUE TITLE
论文效果及滤波问题

### ISSUE THREAD

**Issue by Lollipopwz** [TJCVRS/DVCNN_Lane_Detection#1]
您好，您是否完整复现了这篇paper，是否有效果图可以展示一下？
我感觉paper中的滤波器似乎有点问题，大概是一个45°倾斜的滤波器，而不是hatlike。
另外，可否把您训练的模型上传一下，我想先试一下算法的效果。

感谢您的工作，代码非常规范，学习了～

**Comment by MaybeShewill-CV** [comment]
@Lollipopwz 论文中的滤波器是一个45度倾斜的滤波器,这个模型工作要求,不方便上传，一旦可以上传以后会上传这个模型　谢谢
