### ISSUE TITLE
How can we run it?

### ISSUE THREAD

**Issue by masouduut94** [TJCVRS/DVCNN_Lane_Detection#3]
The code looks sophisticated, but it has no documentation.

Would you please add some documentation about 
1- requirements, 
2- is it supported by gpu or cpu
3- if there are pretrained models to test?
4- and a demo file would make this awesome!

By the way the LaneNet lane detection repository is awesome.

**Comment by MaybeShewill-CV** [comment]
@masouduut94 This repo is not completed here and no plan to make it complete recently. Sorry:)
